all:
	g++ main.cpp admixture_value.cpp Aminus.cpp analytical_fitting.cpp Aplus.cpp beta.cpp betaminus.cpp betaplus.cpp conduction_dispersion.cpp decompose_wave.cpp dedk.cpp df0dk.cpp df0dz.cpp DOS_value.cpp DOS_value1.cpp f.cpp fH.cpp f0.cpp find_cbm_vbm.cpp find_fermi.cpp FindMinInd.cpp J.cpp kminus.cpp kplus.cpp lambda_e_minus.cpp lambda_e_plus.cpp lambda_i_minus.cpp lambda_i_plus.cpp lambda_o_minus.cpp lambda_o_plus.cpp linspace.cpp make_band.cpp mu_elastic.cpp mu_overall.cpp mu_po.cpp mu_elasticH.cpp mu_overallH.cpp mu_poH.cpp n_DOS.cpp N_poph.cpp nu_alloy1.cpp nu_de.cpp nu_dis.cpp nu_ii.cpp nu_im.cpp nu_pe.cpp polyfit1.cpp polyval.cpp read_fermi.cpp read_input.cpp read_input_file.cpp read_OUTCAR.cpp read_ispin.cpp rsquare.cpp copyright.cpp -o AMMCR

clean:
	rm -f *.o mobility.dat conductivity.dat themopower.dat scattering_rate.dat g.dat  conduction_band.dat valence_band.dat mobility_up_spin.dat conductivity_up_spin.dat thermopower_up_spin.dat scattering_rate_up_spin.dat g_up_spin.dat  conduction_band_up_spin.dat valence_band_up_spin.dat  mobility_down_spin.dat conductivity_down_spin.dat thermopower_down_spin.dat scattering_rate_down_spin.dat g_down_spin.dat  conduction_band_down_spin.dat valence_band_down_spin.dat 

		
	
